### ISSUE TITLE
Wheel of fortune DX crashes game.

### ISSUE THREAD

**Issue by tetraminus** [JeffVi/DX-Tarots#1]
using wheel of fortune DX crashes game.
stack trace:
<img width="1252" alt="Screenshot 2024-04-08 at 8 46 51 AM" src="https://github.com/JeffVi/DX-Tarots/assets/54343976/ff3215fb-8193-44f5-85ec-f49bf1dd1fb1">
gamestate:
<img width="1440" alt="Screenshot 2024-04-08 at 8 47 33 AM" src="https://github.com/JeffVi/DX-Tarots/assets/54343976/a81ea1ca-d910-43f7-b37d-26382e4c4639">

seems to crash on line 1498 of the mod file. the table passed into the pseudorandom_element function is instead a bool.

**Comment by tetraminus** [comment]
did some testing, found a fix. I'll put in a pull request soon.

**Comment by JeffVi** [comment]
Thanks for the fix !
