### ISSUE TITLE
The Plant curse can debuff Jokers when using Pareidolia

### ISSUE THREAD

**Issue by GauntletGames-2086** [JeffVi/DX-Tarots#11]
There is no check for the cardarea to not be G.jokers, resulting in the chance that Jokers can get debuffed with Pareidolia due to `is_face` function returning true. 

![image](https://github.com/user-attachments/assets/7e3f6a87-c0c0-471c-98b0-ca232a66099a)

**Comment by JeffVi** [comment]
Should be fixed with [4d8700c](https://github.com/JeffVi/DX-Tarots/commit/4d8700ce17e1f0c7d4388383ffc8d4e81f1a8730)
