### ISSUE TITLE
[BUG] Crash during startup on latest

### ISSUE THREAD

**Issue by thelmexx** [JeffVi/DX-Tarots#14]
### Issue
Game crashes on startup on the current version of Balatro with latest DX Tarots and Steamodded/Lovely.
### Steps to reproduce
1. Verify files on steam for a clean install.
2. Install Lovely 0.5.0-beta7 and Steamodded 1.0.0~ALPHA-0924a
3. Download and install the latest version of DX Tarots from [here](https://github.com/JeffVi/DX-Tarots/blob/master/TarotDx.lua)
4. Run Balatro.
### Expected Behavior
Game opens to main menu with DX Tarots installed.
### Current Behavior
Game crashes before reaching the splash screen [errors](https://pastebin.com/C779BnXW)

**Comment by Johan482** [comment]
Same here.
I just commented out the loadCursesModule() call and set the chance of the curses appearing to 0.
No Curses for me but at least the rest seems to work.

![Screenshot from 2024-10-05 23-21-50](https://github.com/user-attachments/assets/ba3fd3c0-0bd1-42ed-9350-99293c08b0a9)

**Comment by JeffVi** [comment]
Will be fixed with #15
