### ISSUE TITLE
Codex Arcanum's Oil is both broken and incompatible

### ISSUE THREAD

**Issue by english5040** [JeffVi/DX-Tarots#8]
Codex Arcanum's Oil has multiple bugs as it stands, including:
- `card.config.oil` is not saved when exiting the game
- When copying cards, the effect of Oil is not copied

This makes it hard to correctly write Oil DX and other Oil compatibility code.

In addition Oil calls card:set_debuff(false) directly, which is hard to make work with DX Tarot's current code.

**Comment by JeffVi** [comment]
Need some more testing but this should be fixed

**Comment by english5040** [comment]
ability.oil is set after set_debuff which is incorrect, I think.
Also did we overwrite the original Oil?

**Comment by JeffVi** [comment]
Fixed in [5f36e37](https://github.com/JeffVi/DX-Tarots/commit/5f36e3731b385841a5bf3495738350a57bacbb10), thanks
And yes the overwrite already existed [see here](https://github.com/JeffVi/DX-Tarots/blob/5f36e3731b385841a5bf3495738350a57bacbb10/source/alchemical_dx.lua#L1196)
